
Add-Type -AssemblyName System.Drawing
$jpegEncoder = [System.Drawing.Imaging.ImageCodecInfo]::GetImageEncoders() | Where-Object { $_.MimeType -eq 'image/jpeg' }
$encoderParams = New-Object System.Drawing.Imaging.EncoderParameters(1)
$encoderParams.Param[0] = New-Object System.Drawing.Imaging.EncoderParameter([System.Drawing.Imaging.Encoder]::Quality, 92L)

$files = @(
  @{ Src = 'C:\\Nam 2026\\Web app\\DANH SACH CAC APP WEB DA THUC HIÊN\\Hinh ảnh minh hoa cho ung dung\\Nuoi duong be 0 -60 tháng\\Tinh nang 1.png'; DestFeature = 'C:\\Nam 2026\\Web app\\DANH SACH CAC APP WEB DA THUC HIÊN\\public\\apps\\nuoi-duong-be-0-60\\feature_01_screen.jpg'; DestNamed = 'C:\\Nam 2026\\Web app\\DANH SACH CAC APP WEB DA THUC HIÊN\\public\\apps\\nuoi-duong-be-0-60\\feature_01_home_dashboard_smart_logging.jpg'; DestScreen = 'C:\\Nam 2026\\Web app\\DANH SACH CAC APP WEB DA THUC HIÊN\\public\\apps\\nuoi-duong-be-0-60\\screen-1.jpg'; Num = 1 },
  @{ Src = 'C:\\Nam 2026\\Web app\\DANH SACH CAC APP WEB DA THUC HIÊN\\Hinh ảnh minh hoa cho ung dung\\Nuoi duong be 0 -60 tháng\\Tinh nang 2.png'; DestFeature = 'C:\\Nam 2026\\Web app\\DANH SACH CAC APP WEB DA THUC HIÊN\\public\\apps\\nuoi-duong-be-0-60\\feature_02_screen.jpg'; DestNamed = 'C:\\Nam 2026\\Web app\\DANH SACH CAC APP WEB DA THUC HIÊN\\public\\apps\\nuoi-duong-be-0-60\\feature_02_growth_engine.jpg'; DestScreen = 'C:\\Nam 2026\\Web app\\DANH SACH CAC APP WEB DA THUC HIÊN\\public\\apps\\nuoi-duong-be-0-60\\screen-2.jpg'; Num = 2 },
  @{ Src = 'C:\\Nam 2026\\Web app\\DANH SACH CAC APP WEB DA THUC HIÊN\\Hinh ảnh minh hoa cho ung dung\\Nuoi duong be 0 -60 tháng\\Tinh nang 3.png'; DestFeature = 'C:\\Nam 2026\\Web app\\DANH SACH CAC APP WEB DA THUC HIÊN\\public\\apps\\nuoi-duong-be-0-60\\feature_03_screen.jpg'; DestNamed = 'C:\\Nam 2026\\Web app\\DANH SACH CAC APP WEB DA THUC HIÊN\\public\\apps\\nuoi-duong-be-0-60\\feature_03_development_center.jpg'; DestScreen = 'C:\\Nam 2026\\Web app\\DANH SACH CAC APP WEB DA THUC HIÊN\\public\\apps\\nuoi-duong-be-0-60\\screen-3.jpg'; Num = 3 },
  @{ Src = 'C:\\Nam 2026\\Web app\\DANH SACH CAC APP WEB DA THUC HIÊN\\Hinh ảnh minh hoa cho ung dung\\Nuoi duong be 0 -60 tháng\\Tinh nang 4.png'; DestFeature = 'C:\\Nam 2026\\Web app\\DANH SACH CAC APP WEB DA THUC HIÊN\\public\\apps\\nuoi-duong-be-0-60\\feature_04_screen.jpg'; DestNamed = 'C:\\Nam 2026\\Web app\\DANH SACH CAC APP WEB DA THUC HIÊN\\public\\apps\\nuoi-duong-be-0-60\\feature_04_nutrition_meal_planner.jpg'; DestScreen = 'C:\\Nam 2026\\Web app\\DANH SACH CAC APP WEB DA THUC HIÊN\\public\\apps\\nuoi-duong-be-0-60\\screen-4.jpg'; Num = 4 },
  @{ Src = 'C:\\Nam 2026\\Web app\\DANH SACH CAC APP WEB DA THUC HIÊN\\Hinh ảnh minh hoa cho ung dung\\Nuoi duong be 0 -60 tháng\\tinh nang 5.png'; DestFeature = 'C:\\Nam 2026\\Web app\\DANH SACH CAC APP WEB DA THUC HIÊN\\public\\apps\\nuoi-duong-be-0-60\\feature_05_screen.jpg'; DestNamed = 'C:\\Nam 2026\\Web app\\DANH SACH CAC APP WEB DA THUC HIÊN\\public\\apps\\nuoi-duong-be-0-60\\feature_05_offline_emergency_sos.jpg'; DestScreen = 'C:\\Nam 2026\\Web app\\DANH SACH CAC APP WEB DA THUC HIÊN\\public\\apps\\nuoi-duong-be-0-60\\screen-5.jpg'; Num = 5 },
  @{ Src = 'C:\\Nam 2026\\Web app\\DANH SACH CAC APP WEB DA THUC HIÊN\\Hinh ảnh minh hoa cho ung dung\\Nuoi duong be 0 -60 tháng\\tinh nang 6.png'; DestFeature = 'C:\\Nam 2026\\Web app\\DANH SACH CAC APP WEB DA THUC HIÊN\\public\\apps\\nuoi-duong-be-0-60\\feature_06_screen.jpg'; DestNamed = 'C:\\Nam 2026\\Web app\\DANH SACH CAC APP WEB DA THUC HIÊN\\public\\apps\\nuoi-duong-be-0-60\\feature_06_vaccination_smart_reminders.jpg'; DestScreen = 'C:\\Nam 2026\\Web app\\DANH SACH CAC APP WEB DA THUC HIÊN\\public\\apps\\nuoi-duong-be-0-60\\screen-6.jpg'; Num = 6 },
  @{ Src = 'C:\\Nam 2026\\Web app\\DANH SACH CAC APP WEB DA THUC HIÊN\\Hinh ảnh minh hoa cho ung dung\\Nuoi duong be 0 -60 tháng\\Tinh nang 7.png'; DestFeature = 'C:\\Nam 2026\\Web app\\DANH SACH CAC APP WEB DA THUC HIÊN\\public\\apps\\nuoi-duong-be-0-60\\feature_07_screen.jpg'; DestNamed = 'C:\\Nam 2026\\Web app\\DANH SACH CAC APP WEB DA THUC HIÊN\\public\\apps\\nuoi-duong-be-0-60\\feature_07_digital_family_vault.jpg'; DestScreen = 'C:\\Nam 2026\\Web app\\DANH SACH CAC APP WEB DA THUC HIÊN\\public\\apps\\nuoi-duong-be-0-60\\screen-7.jpg'; Num = 7 },
  @{ Src = 'C:\\Nam 2026\\Web app\\DANH SACH CAC APP WEB DA THUC HIÊN\\Hinh ảnh minh hoa cho ung dung\\Nuoi duong be 0 -60 tháng\\Tinh nang 8.png'; DestFeature = 'C:\\Nam 2026\\Web app\\DANH SACH CAC APP WEB DA THUC HIÊN\\public\\apps\\nuoi-duong-be-0-60\\feature_08_screen.jpg'; DestNamed = 'C:\\Nam 2026\\Web app\\DANH SACH CAC APP WEB DA THUC HIÊN\\public\\apps\\nuoi-duong-be-0-60\\feature_08_ai_parenting_companion.jpg'; DestScreen = 'C:\\Nam 2026\\Web app\\DANH SACH CAC APP WEB DA THUC HIÊN\\public\\apps\\nuoi-duong-be-0-60\\screen-8.jpg'; Num = 8 },
  @{ Src = 'C:\\Nam 2026\\Web app\\DANH SACH CAC APP WEB DA THUC HIÊN\\Hinh ảnh minh hoa cho ung dung\\Nuoi duong be 0 -60 tháng\\Tinh nang 9.png'; DestFeature = 'C:\\Nam 2026\\Web app\\DANH SACH CAC APP WEB DA THUC HIÊN\\public\\apps\\nuoi-duong-be-0-60\\feature_09_screen.jpg'; DestNamed = 'C:\\Nam 2026\\Web app\\DANH SACH CAC APP WEB DA THUC HIÊN\\public\\apps\\nuoi-duong-be-0-60\\feature_09_activity_generator.jpg'; DestScreen = 'C:\\Nam 2026\\Web app\\DANH SACH CAC APP WEB DA THUC HIÊN\\public\\apps\\nuoi-duong-be-0-60\\screen-9.jpg'; Num = 9 },
  @{ Src = 'C:\\Nam 2026\\Web app\\DANH SACH CAC APP WEB DA THUC HIÊN\\Hinh ảnh minh hoa cho ung dung\\Nuoi duong be 0 -60 tháng\\Tinh nang 10.png'; DestFeature = 'C:\\Nam 2026\\Web app\\DANH SACH CAC APP WEB DA THUC HIÊN\\public\\apps\\nuoi-duong-be-0-60\\feature_10_screen.jpg'; DestNamed = 'C:\\Nam 2026\\Web app\\DANH SACH CAC APP WEB DA THUC HIÊN\\public\\apps\\nuoi-duong-be-0-60\\feature_10_smart_family_timeline_journal.jpg'; DestScreen = 'C:\\Nam 2026\\Web app\\DANH SACH CAC APP WEB DA THUC HIÊN\\public\\apps\\nuoi-duong-be-0-60\\screen-10.jpg'; Num = 10 }
)

foreach ($item in $files) {
    Write-Host ("Processing " + $item.Num + ": " + $item.Src)
    $bmp = [System.Drawing.Bitmap]::FromFile($item.Src)
    $bmp.Save($item.DestNamed, $jpegEncoder, $encoderParams)
    $bmp.Save($item.DestFeature, $jpegEncoder, $encoderParams)
    $bmp.Save($item.DestScreen, $jpegEncoder, $encoderParams)
    if ($item.Num -eq 1) {
        $bmp.Save('C:\\Nam 2026\\Web app\\DANH SACH CAC APP WEB DA THUC HIÊN\\public\\apps\\nuoi-duong-be-0-60\\cover.jpg', $jpegEncoder, $encoderParams)
        $bmp.Save('C:\\Nam 2026\\Web app\\DANH SACH CAC APP WEB DA THUC HIÊN\\public\\apps\\nuoi-duong-be-0-60\\real-cover.jpg', $jpegEncoder, $encoderParams)
    }
    $bmp.Dispose()
    Write-Host ("  Saved " + $item.DestNamed)
}
Write-Host "All 10 feature images converted successfully with 100% accuracy!"
